### PR TITLE
Updating the Embassies file

### PR DESCRIPTION
**Pull request by fbidu**
A simple update on the Embassies file. I wonder, however, if it would be nice to add a file listing all of the sources of the files on the repository, a script that automatically updates all of them, the script for conversion and a .gitignore for the intermediate files created on the conversion process.

### CODE REVIEW

**Comment by benbalter** [comment]
@fbidu thanks for this. Where are you getting the update from? The original data originally came from data.dc.gov and was converted using http://ben.balter.com/2013/06/26/how-to-convert-shapefiles-to-geojson-for-use-on-github/.

**Comment by fbidu** [comment]
@benbalter I followed the instructions to access http://data.dc.gov/Main_DataCatalog.aspx which gave me an 404 error so I went to http://data.dc.gov/, searched for `embassies` and grabbed the data from [here](http://opendata.dc.gov/datasets/65b97e8d1f194cdca97fd6219433e142_0). After downloading, I converted using the [geojson-conversion.sh script](https://gist.github.com/benbalter/5858851)

**Comment by benbalter** [comment]
@fbidu thanks again for this, and sorry for the slow reply. Inspired by your pull request, I added https://github.com/benbalter/dc-maps/blob/master/script/setup to update *all* the files from the data catalog. Thanks!

**Comment by fbidu** [comment]
@benbalter Amazing! Thank you.

**Pull request closed without merging**
